kinoman/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from main.views import IndexView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='index'),
    path('main/', include('main.urls', namespace='main')),
    path('users/', include('users.urls', namespace='users'))
]

if settings.DEBUG:
    urlpatterns.append(path("__debug__/", include("debug_toolbar.urls")))
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path, re_path

from main.views import (FilmsView, NewsListView, RaitingView,
                        SearchResultsView, SerialsView, film_detail_view,
                        news_detail_view)

app_name = 'main'

urlpatterns = [
    path('films/', FilmsView.as_view(), name='films'),
    path('page/<int:page>/', FilmsView.as_view(), name='paginator'),
    path('serials/', SerialsView.as_view(), name='serials'),
    path('raiting/', RaitingView.as_view(), name='raiting'),
    path('category/', RaitingView.as_view(), name='category'),
    path('search/', SearchResultsView.as_view(), name='search_results'),
    path('search/', SearchResultsView.as_view(), name='search_results'),
    re_path(r'^show/(?P<film_id>[-\w]*)/$', film_detail_view, name='show'),
    path('news/', NewsListView.as_view(), name='news_list'),
    re_path(r'^news/(?P<news_id>[-\w]*)/$', news_detail_view, name='news'),
]

users/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from users.views import (EmailVerificationView, UserLoginView, UserProfileView,
                         UserRegistrationView)

app_name = 'users'

urlpatterns = [
    path('login/', UserLoginView.as_view(), name='login'),
    path('registration/', UserRegistrationView.as_view(), name='registration'),
    path('profile/<int:pk>/', UserProfileView.as_view(), name='profile'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('verify/<str:email>/<uuid:code>', EmailVerificationView.as_view(), name='email_verification'),
]

main/models.py
from django.db import models

from users.models import User


class Category(models.Model):
    name = models.CharField(max_length=64, unique=True, primary_key=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'category'
        verbose_name_plural = 'categories'




class Genre(models.Model):
    name = models.CharField(max_length=64, unique=True, primary_key=True)

    def __str__(self):
        return self.name

class Film(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=128, unique=False, primary_key=False)
    desc = models.TextField(max_length=320)
    genre = models.ForeignKey(to=Genre, on_delete=models.SET_DEFAULT, default='Боевик')
    video = models.CharField(max_length=256, default='Пусто')
    image = models.ImageField(upload_to='main_images')
    category = models.ForeignKey(to=Category, on_delete=models.SET_DEFAULT, default='Фильмы')
    raiting = models.FloatField(default=0)
    year = models.IntegerField(default=0)
    director = models.CharField(max_length=128, default='Пусто')

    def __str__(self):
        return f'{self.name} | {self.category.name}'

class CommentModel(models.Model):
    film = models.ForeignKey(to=Film, related_name='comments', on_delete=models.CASCADE)
    user = models.ForeignKey(to=User, on_delete=models.CASCADE)
    text = models.TextField()
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return 'Комментарий от {} для {}'.format(self.user, self.film)

class News(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=32)
    text = models.TextField()
    created = models.DateTimeField(auto_now_add=True)

main/forms.py
from django import forms

from main.models import CommentModel


class CommentForm(forms.ModelForm):
    text = forms.CharField(widget=forms.TextInput())
    class Meta:
        model = CommentModel
        fields = ('user', 'text',)

main/views.py
from django.db.models import Q
from django.shortcuts import render
from django.views.generic.base import TemplateView
from django.views.generic.list import ListView

from common.views import TitleMixin
from main.forms import CommentForm
from main.models import Film, News
from users.models import User


class BaseView(TemplateView):
    template_name = 'main/base.html'

    def get_context_data(self, **kwargs):
        context = super(BaseView, self).get_context_data()
        context['films'] = Film.objects.filter(category="Фильмы")
        return context

class IndexView(TitleMixin, TemplateView):
    template_name = 'main/index.html'
    title = 'КиноМан'

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data()
        context["serials"] = Film.objects.filter(category="Сериалы").order_by("-id")
        context['films'] = Film.objects.filter(category="Фильмы").order_by("-id")
        return context

class FilmsView(TitleMixin, ListView):
    model = Film
    template_name = 'main/films.html'
    title = 'КиноМан | Фильмы'

    def get_queryset(self):
        queryset = super(FilmsView, self).get_queryset()
        return queryset

    def get_context_data(self, **kwargs):
        context = super(FilmsView, self).get_context_data()
        context['films'] = Film.objects.filter(category="Фильмы")
        return context

class SerialsView(TitleMixin, ListView):
    model = Film
    template_name = 'main/serials.html'
    title = 'КиноМан | Сериалы'

    def get_queryset(self):
        queryset = super(SerialsView, self).get_queryset()
        return queryset

    def get_context_data(self, **kwargs):
        context = super(SerialsView, self).get_context_data()
        context['serials'] = Film.objects.filter(category="Сериалы")
        return context

class RaitingView(TitleMixin, ListView):
    model = Film
    title = 'Киноман | Рейтинг'
    template_name = 'main/raiting.html'

    def get_context_data(self, **kwargs):
        context = super(RaitingView, self).get_context_data()
        context['films'] = Film.objects.order_by('-raiting')
        return context


def film_detail_view(request, film_id):
    film = Film.objects.get(id=film_id)
    try:
        user = User.objects.get(id=request.user.id)
    except Exception:
        user = 'k'
    # Комментарии
    comments = film.comments.filter(film=film)

    if request.method == 'POST':
        comment_form = CommentForm(data={'user': user, 'text': request.POST['text']})
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.film = film
            new_comment.user = user
            new_comment.save()

    else:
        comment_form = CommentForm()
    print(comment_form.errors)
    print(request.user)

    return render(request, 'main/show.html',
                  context={
                      'user': user,
                      'film': film,
                      'comments': comments,
                      'comment_form': comment_form,
                  })



class SearchResultsView(ListView):
    model = Film
    template_name = 'main/search_results.html'

    def get_queryset(self):
        query = self.request.GET.get('search_field')
        object_list = Film.objects.filter(
            Q(name__icontains=query)
        )
        return object_list

class NewsListView(ListView):
    model = News
    template_name = 'main/news_list.html'

    def get_queryset(self):
        queryset = super(NewsListView, self).get_queryset()
        return queryset

    def get_context_data(self, **kwargs):
        context = super(NewsListView, self).get_context_data()
        context['news_list'] = News.objects.order_by('-id')
        return context


def news_detail_view(request, news_id):
    news = News.objects.get(id=news_id)

    return render(request, 'main/news.html',
                  context={
                      'news': news,
                  })

main/templates/main/base.html
{% load static %}
<!DOCTYPE html>


<html lang="ru">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>{{ title }}</title>
	<meta name="description" content="Киноман - это портал о кино" />
	<meta name="keywords" content="фильмы, фильмы онлайн, hd" />
	{% block css %} {% endblock %}
</head>
<body>

	<div class="main">


			<div class="header">
			<div class="logo">
				<div class="logo_text">
					<h1><a href="{% url 'index' %}">КиноМан</a></h1>
					<h2>Кино - наша страсть!</h2>
				</div>
			</div>

			<div class="menubar">

				{% block menu %} {% endblock %}

				<div class="login">
					{% if user.is_authenticated %}
						<a class="profile-buttons" href="{% url 'users:profile' user.id %}">Профиль</a>
						<a class="profile-buttons" href="{% url 'users:logout' %}">Выйти</a>
					{% else %}
						<a class="profile-buttons" href="{% url 'users:login' %}">Войти</a>
					{% endif %}


			</div>

			</div>
			<div class="search_block">

				<h2 id="search-text">Поиск</h2>
		<form method="get" action="{% url 'main:search_results' %}" id="search_form">
			{% csrf_token %}
			<input type="search" name="search_field" placeholder="Ваш запрос"/>
<!--		   <input type="submit" class="btn" value="Найти">-->


		</form>

			</div>


		</div>

		<div class="site_content">

			<div class="sidebar_contained">

				<div class="sidebar">
					<h2><a href="{% url 'main:news_list' %}" style="text-decoration: none; color: #136cb2;">Новости</a></h2>
					{% for news in sidebar_news %}
						<div style="padding-bottom: 30px;">
							<span style="font-size: 0.85em">{{ news.created }}</span>
							<p>"{{ news.name }}"</p>
							<a href="{% url 'main:news' news.id %}">Читать</a>
						</div>
					{% endfor %}
				</div>
				<div class="sidebar">
					<h2> <a href="{% url 'main:raiting' %}" style="text-decoration: none; color: #136cb2;">Рейтинг фильмов</a> </h2>
					{% for film in sidebar_films %}
						<ul>
							<li><a href="{% url 'main:show' film.id %}">{{ film.name }}</a><span class="rating_sidebar">{{ film.raiting }}</li>
						</ul>
					{% endfor %}
				</div>
			</div>


		{% block content %} {% endblock %}

	</div>







<div class="footer">
	<p>
		<a href="{% url 'index' %}">Главная</a> |
		<a href="{% url 'main:films' %}">Фильмы</a> |
		<a href="{% url 'main:serials' %}">Сериалы</a> |
		<a href="{% url 'main:raiting' %}">Топ фильмов и сериалов</a> |
	</p>
	<p>wh-db.com 2019</p>
</div>
</div>

</body>
</html>

main/templates/main/films.html
{% extends 'main/base.html' %}
{% load static %}
{% load cache %}

{% block css %}
	<link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
{% endblock %}

{% block menu %}
	<ul class="menu">
					<li><a href="{% url 'index' %}">Главная</a></li>
					<li class="selected"><a href="{% url 'main:films' %}">Фильмы</a></li>
					<li><a href="{% url 'main:serials' %}">Сериалы</a></li>
					<li><a href="{% url 'main:raiting' %}">Топ фильмов и сериалов</a></li>
				</ul>
{% endblock %}

{% block content %}
	<div class="content">
						{% cache 30 films %}
						{% for film in films %}
						<div class="info_film">

						<a href="{% url 'main:show' film.id %}"><img src="{{ film.image.url }}"></a>
						<h2>{{ film.name }}</h2>
						<p>{{ film.desc }}</p>
					    <div class="button"><a href="{% url 'main:show' film.id %}">
					    Смотреть</a></div>

					</div>
						{% endfor %}
					{% endcache %}



	</div>
{% endblock %}

main/templates/main/index.html
{% extends 'main/base.html' %}
{% load static %}
<!DOCTYPE html>

{% block css %}
	<link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
{% endblock %}

{% block menu %}
	<ul class="menu">
					<li class="selected"><a href="{% url 'index' %}">Главная</a></li>
					<li><a href="{% url 'main:films' %}">Фильмы</a></li>
					<li><a href="{% url 'main:serials' %}">Сериалы</a></li>
					<li><a href="{% url 'main:raiting' %}">Топ фильмов и сериалов</a></li>
				</ul>
{% endblock %}

{% block content %}
	<div class="content">

			<h1>Новые фильмы</h1>

			<div class="films_block">
				{% for film in films %}
					<a href="{% url 'main:show' film.id %}"><img src="{{ film.image.url }}" class="film"></a>
<!--					<a href="{% url 'main:show' film.id %}"><img src="{{ film.image.url }}" class="film"></a>-->
<!--					<a href="{% url 'main:show' film.id %}"><img src="{{ film.image.url }}" class="film"></a>-->
<!--					<a href="{% url 'main:show' film.id %}"><img src="{{ film.image.url }}" class="film"></a>-->
				{% endfor %}
			</div>

			<h1>Новые сериалы</h1>

			<div class="films_block">
				{% for serial in serials %}
					<a href="{% url 'main:show' serial.id %}"><img src="{{ serial.image.url }}" class="film"></a>
<!--					<a href="{% url 'main:show' serial.id %}"><img src="{{ serial.image.url }}" class="film"></a>-->
<!--					<a href="{% url 'main:show' serial.id %}"><img src="{{ serial.image.url }}" class="film"></a>-->
<!--					<a href="{% url 'main:show' serial.id %}"><img src="{{ serial.image.url }}" class="film"></a>-->
				{% endfor %}
			</div>
			{% for news in sidebar_news %}
				<div style="padding-bottom: 20px;" class="posts">

					<hr>
				   <h2><a href="{% url 'main:news' news.id %}">{{ news.name }}</a></h2>
				   <div class="posts_content">
					<p style="white-space: nowrap;
									  overflow: hidden;
									  text-overflow: ellipsis;">
							  {{ news.text }}</p>
				   </div>
					<a style="padding-bottom: 10px; font-size: 0.93em;" href="{% url 'main:news' news.id %}" id="chitat">читать</a>
				</div>


			{% endfor %}




		</div>
{% endblock %}

main/templates/main/news.html
{% extends 'main/base.html' %}
{% load static %}

{% block css %}
	<link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
{% endblock %}

{% block menu %}
	<ul class="menu">
					<li><a href="{% url 'index' %}">Главная</a></li>
					<li><a href="{% url 'main:films' %}">Фильмы</a></li>
					<li><a href="{% url 'main:serials' %}">Сериалы</a></li>
					<li><a href="{% url 'main:raiting' %}">Топ фильмов и сериалов</a></li>
				</ul>
{% endblock %}

{% block content %}
	<div class="content">
		<p style="color: #aba9a4;">{{ news.created }}</p>
        <h2>{{ news.name }}</h2>

			<div class="description_film">
				<p>{{ news.text }}</p>
			</div>
        </div>




    </div>
{% endblock %}

main/templates/main/news_list.html
{% extends 'main/base.html' %}
{% load static %}

<!DOCTYPE html>

{% block css %}
	<link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
{% endblock %}

{% block menu %}
	<ul class="menu">
					<li><a href="{% url 'index' %}">Главная</a></li>
					<li><a href="{% url 'main:films' %}">Фильмы</a></li>
					<li><a href="{% url 'main:serials' %}">Сериалы</a></li>
					<li><a href="{% url 'main:raiting' %}">Топ фильмов и сериалов</a></li>
				</ul>
{% endblock %}

{% block content %}

<div class="content">
	<h1>Новости</h1>
  {% for news in news_list %}
						<div style="background-color: #f9f9f9; padding: 5%; height: 180px;">
						<h2>{{ news.name }}</h2>
						<p style="white-space: nowrap;
                                  overflow: hidden;
                                  text-overflow: ellipsis;">
                          {{ news.text }}</p>
					    <div class="button"><a href="{% url 'main:news' news.id %}">
					    Читать</a></div>

					</div>

  {% endfor %}
</div>
{% endblock %}

main/templates/main/raiting.html
{% extends 'main/base.html' %}
{% load static %}

{% block css %}
	<link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
{% endblock %}

{% block menu %}
	<ul class="menu">
					<li><a href="{% url 'index' %}">Главная</a></li>
					<li><a href="{% url 'main:films' %}">Фильмы</a></li>
					<li><a href="{% url 'main:serials' %}">Сериалы</a></li>
					<li class="selected"><a href="{% url 'main:raiting' %}">Топ фильмов и сериалов</a></li>
				</ul>
{% endblock %}

{% block content %}
	<div class="content" style="align: left;">
				<table style="align: left;">
					{% for film in films %}

					<tr>

						<th></th>
						<th></th>
						<th class="center">Рейтинг</th>

					</tr>
					<tr>

						<td width="155px" height="240px"><img src="{{ film.image.url }}" style="width: 160px; height: 240px;"></td>
						<td style="font-size: 1.5em; align: center; width: 250px;">{{ forloop.counter }}. <a href="{% url 'main:show' film.id %}">{{ film.name }}</a></td>
						<td class="center rating" style="width: 100px; font-size: 1.3em;">{{ film.raiting }}</td>

					</tr>

					{% endfor %}
				</table>

			</div>
{% endblock %}

main/templates/main/search_results.html
{% extends 'main/base.html' %}
{% load static %}
{% load cache %}

{% block css %}
	<link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
{% endblock %}

{% block menu %}
	<ul class="menu">
					<li><a href="{% url 'index' %}">Главная</a></li>
					<li class="selected"><a href="{% url 'main:films' %}">Фильмы</a></li>
					<li><a href="{% url 'main:serials' %}">Сериалы</a></li>
					<li><a href="{% url 'main:raiting' %}">Топ фильмов и сериалов</a></li>
				</ul>
{% endblock %}

{% block content %}

<div class="content">
	<h1>Результаты поиска:</h1>
  {% for film in object_list %}
						<div class="info_film">

						<img src="{{ film.image.url }}">
						<h2>{{ film.name }}</h2>
						<p>{{ film.desc }}</p>
					    <div class="button"><a href="{% url 'main:show' film.id %}">
					    Смотреть</a></div>

					</div>

  {% endfor %}
</div>
{% endblock %}

main/templates/main/serials.html
{% extends 'main/base.html' %}
{% load static %}
{% load cache %}

{% block css %}
	<link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
{% endblock %}

{% block menu %}
	<ul class="menu">
					<li><a href="{% url 'index' %}">Главная</a></li>
					<li><a href="{% url 'main:films' %}">Фильмы</a></li>
					<li class="selected"><a href="{% url 'main:serials' %}">Сериалы</a></li>
					<li><a href="{% url 'main:raiting' %}">Топ фильмов и сериалов</a></li>
				</ul>
{% endblock %}


{% block content %}
	<div class="content">
						{% cache 30 serials %}
						{% for serial in serials %}
						<div class="info_film">

						<a href="{% url 'main:show' serial.id %}"><img src="{{ serial.image.url }}"></a>
						<h2>{{ serial.name }}</h2>
						<p>{{ serial.desc }}</p>
					    <div class="button"><a href="{% url 'main:show' serial.id %}">
					    Смотреть</a></div>

					</div>
						{% endfor %}
					{% endcache %}




				</div>
{% endblock %}

main/templates/main/show.html
{% extends 'main/base.html' %}
{% load static %}

{% block css %}
	<link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
{% endblock %}

{% block menu %}
	<ul class="menu">
					<li><a href="{% url 'index' %}">Главная</a></li>
					<li><a href="{% url 'main:films' %}">Фильмы</a></li>
					<li><a href="{% url 'main:serials' %}">Сериалы</a></li>
					<li><a href="{% url 'main:raiting' %}">Топ фильмов и сериалов</a></li>
				</ul>
{% endblock %}

{% block content %}
	<div class="content">

			<h1>{{ film.name }}</h1>

			<div class="trailer">
				<iframe width="560" height="315"
						src="{{ film.video }}"
						title="YouTube video player" frameborder="0"
						allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
						allowfullscreen></iframe>
			</div>

			<div class="info_film_page">

				<span class="label">Рейтинг:</span><span class="value">{{ film.raiting }}</span><br><br>
				<span class="label">Жанр:</span><span class="value">{{ film.genre }}</span><br>
				<span class="label">Год:</span><span class="value">{{ film.year }}</span><br>
				<span class="label">Режиссер:</span><span class="value">{{ film.director }}</span>
			</div>

			<hr>





			<h2>Описание</h2>
			<div class="description_film">
				<p>{{ film.desc }}</p>
			</div>



			<h2>Комментарии к {{ film.name }}</h2>
			<div class="reviews">
				{% for comment in comments %}

					<div class="review_name">
						{{ comment.user.username }}
					</div>
					<div class="review_text">
						{{ comment.text }}
					</div>
				{% empty %}
					<p>Комментариев пока нет</p>
				{% endfor %}

			</div>
			{% if user.is_authenticated %}
				<script src="{% static 'assets/js/not_refresh.js' %}"></script>
				<div class="send">

					<form method="post" action="." id="review" enctype= multipart/form-data autocomplete="off" onsubmit="return submitForm()">

						{{ comment_form.text }}
						{% csrf_token %}

						<p><input type="submit" value="Отправить"></p>

	<!--					<textarea name="review_text" placeholder="Ваш комментарий"></textarea>-->
	<!--					<input type="submit" class="btn" value="Отправить">-->

					</form>

				</div>
			{% else %}
				<p style="font-size: 25px;"><a href="{% url 'users:login' %}">Войдите</a>
					или <a href="{% url 'users:registration' %}">Зарегистрируйтесь</a>
					чтобы оставлять комментарии</p>
				<hr>
				<hr>
			{% endif %}

		</div>
{% endblock %}